### ISSUE TITLE
Where to find fosscord in the discord client? 

### ISSUE THREAD

**Issue by yemix** [MaddyUnderStars/Fosscord-BD#12]

**Comment by MaddyUnderStars** [comment]
I'm not sure what you mean?

Once you've installed the plugin, you'll find a new `Fosscord` menu in powercord's settings, or in betterdiscord you'll see a `Fosscord` plugin and a settings icon next to it in the Plugins menu. You add an instance api url and your login details ( token or username/password ), and the client will connect. You can't yet make guilds in the plugin, so you need to make/join them through the web client.

**Comment by yemix** [comment]
i dont find any fosscord related infos in my discord client (betterdiscord)

**Comment by MaddyUnderStars** [comment]
Have you installed the plugin? Put it in your plugins folder ( you can find it by going to settings -> plugins -> open plugins folder in BetterDiscord ). After you've done that you'll find the Fosscord plugin in settings -> plugins. Enable it and follow my steps above, or the guide in the readme.
